version: '3.8'

services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - nexa-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: users_db
    networks:
      - nexa-network

  redis-master:
    image: redis:latest
    container_name: redis-master
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - nexa-network

  redis-replica-1:
    image: redis:latest
    container_name: redis-replica-1
    command: redis-server --replicaof redis-master 6379
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - nexa-network

  redis-sentinel:
    image: redis:latest
    container_name: redis-sentinel
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
    networks:
      - nexa-network

volumes:
  mongodb_data:

networks:
  nexa-network:
    driver: bridge
